CREATE USER KHLOVE IDENTIFIED BY KHLOVE;
GRANT CONNECT TO KHLOVE;

CREATE USER KHUSER IDENTIFIED BY KHUSER; -- id및 비밀번호 생성
GRANT CONNECT TO KHUSER; --유저 접속권한 부여

CREATE USER KHUSER IDENTIFIED BY KHUSER;

GRANT RESOURCE TO KHLOVE;

CREATE user scott IDENTIFIED BY scott;
GRANT CONNEcT to scott;
grant resource to scott;

