CREATE TABLE LOVER(
    LOVER_ID VARCHAR2(20),
    LOVER_PWD VARCHAR2(20),
    LOVER_AGE NUMBER,
    LOVER_DATE DATE

);


DROP TABLE LOVER;

INSERT INTO LOVER(LOVER_ID, LOVER_PWD, LOVER_AGE, LOVER_DATE)
VALUES('khuser01', 'pass01', 33, SYSDATE);
INSERT INTO LOVER VALUES('khuser02', 'pass02', 22, SYSDATE);
INSERT INTO LOVER VALUES('khuser03', 'pass03', 44, SYSDATE);

SELECT LOVER_ID, LOVER_PWD, LOVER_AGE, LOVER_DATE
FROM LOVER;

DELETE
FROM LOVER
WHERE LOVER_ID = 'khuser01';

UPDATE LOVER
set LOVER_ID = 'khuser00'
WHERE LOVER_ID = 'khuser01';

UPDATE LOVER
set LOVER_ID = 'khuser04'
WHERE LOVER_ID is null;
